config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get '/wechats_redirect', to: 'wechats#redirect'

  resource :wechat, only: [:show, :create]
  resources :songs

  devise_for :users
  resources :users, shallow: true do
    resources :albums
    resources :images
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :albums
  has_many :images, :through => :albums

  validates :nickname, :subscribe_time, presence: true
  validates :openid, uniqueness: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #:recoverable, :rememberable, :trackable,
  devise :database_authenticatable, :registerable, :validatable

  def latest_album
    if albums.unpublished.count > 0
      albums.unpublished.last
    else
      albums.create song: Song.second
    end
  end

  def sex
    case super
    when 1
      "男"
    when 2
      "女"
    else
      "性别未知"
    end
  end

  def subscribe_time
    Time.at(super).strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.where(subscribe: true)
    @unsubscribed = User.all.where(subscribe: false)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
      params.require(:user).permit(:subscribe, :openid, :nickname, :sex, :language, :city, :province,
                                   :country, :headimgurl, :subscribe_time, :unionid, :remark, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-12 columns">
      <label>does user subscribed?</label>
        <%= f.check_box :subscribe %>
        <%= label_tag(:user_subscribe, "Yes") %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>openid
        <%= f.text_field :openid %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>nickname
        <%= f.text_field :nickname %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
        <label>choose your sex </label>
        <%= f.radio_button :sex, "1" %>
        <%= label_tag(:user_sex_1, "male") %>
        <%= f.radio_button :sex, "2" %>
        <%= label_tag(:user_sex_2, "female") %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>language
        <%= f.text_field :language %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>city
        <%= f.text_field :city %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>province
        <%= f.text_field :province %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>country
        <%= f.text_field :country %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>headimgurl
        <%= f.text_field :headimgurl %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>subscribe_time
        <%= f.text_field :subscribe_time %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>unionid
        <%= f.text_field :unionid %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>remark
        <%= f.text_field :remark %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h3>正在关注: <%= @users.count %>, 已取消: <%= @unsubscribed.count %></h3>

<ul class="small-block-grid-3">
<% @users.each do |user| %>
  <li>
    <ul>
      <li><b><%= user.nickname %></b></li>
      <li><%= user.subscribe_time %></li>
      <li><%= user.sex %>, 海报: <%= user.albums.count %></li>
      <li><%= user.city %>, <%= user.province %></li>
      <li>
        <span><%= link_to '详情', user %></span>
        <span><%= link_to '编辑', edit_user_path(user) %></span>
        <span><%= link_to '删除', user, method: :delete, data: { confirm: '确定删除该用户?' } %></span>
        <span><%= link_to '相册', user_albums_path(user) %></span>
      </li>
    </ul>
  </li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form' %>

<div class="row">
  <div class="small-12 columns">
    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Back', users_path %>
  </div>
</div>