config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get '/wechats_redirect', to: 'wechats#redirect'

  resource :wechat, only: [:show, :create]
  resources :songs

  devise_for :users
  resources :users, shallow: true do
    resources :albums
    resources :images
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
  has_many :images

  enum status: [ :unpublished, :published ]
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  wechat_responder

  before_action :set_user, only: [:new, :create, :index]
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :permit, only: [:index, :edit, :update, :destroy]

  # 覆盖 wechat-rails(wechat_responder引入) 中的检查签名逻辑, 不检查
  skip_before_action :verify_signature, only: [:show, :create]

  # GET /albums
  # GET /albums.json
  def index
    @albums = @user.albums.order("id desc")
    render layout: "album"
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    render layout: "album"
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
    if @album.published?
      redirect_to @album
    else
      @appid = YAML.load_file("config/wechat.yml")[Rails.env].symbolize_keys[:appid]
      @cfg = AlbumsController.wechat.jsapi_ticket.signature(request.original_url)
      @songs = Song.all
      render layout: "album"
    end
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = @user.albums.build(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to user_albums_url(@album.user, params: {openid: @album.user.openid}), notice: '海报已经删除.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_album
      @album = Album.find(params[:id])
    end

    def permit
      return true if user_signed_in?
      owner = @user || @album.user
      if owner.openid != params[:openid]
        flash[:notice] = "你无权访问上一个页面, 已跳转至主页.."
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :desc, :music, :template, :user_id, :song_id, :status)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for [@user, @album] do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-12 columns">
      <label>标题
        <%= f.text_field :name %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <label>描述
        <%= f.text_field :desc %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <ul class="small-block-grid-3">
        <% @album.images.each do |image| %>
          <li>
            <img src="<%= image.url %>">
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/albums/edit.html.erb
<div id="fullpage" class="text-center">
  <% @album.images.each do |image| %>
    <div class="section"><img src="<%= image.url %>"></div>
  <% end %>
</div>

<div class="album arrow-wrapper animated fadeOutUp">
  <p class="arrow"></p>
</div>

<div class="album menus">
  <div class="menu">
    <a id="tpl" href="#" class="btn" data-title="更换模板">模板</a>
  </div>
  <div class="menu">
    <a id="music" href="#" class="btn" data-title="更换音乐">音乐</a>
  </div>
  <div class="menu">
    <a id="pics" href="#" class="btn" data-title="管理相册">相册</a>
  </div>
  <div class="menu">
    <a id="title" href="#" class="btn" data-title="发布">发布</a>
  </div>
</div>

<div class="select-layer">
  <div class="title-bar">
    <h3 class="title"></h3>
    <span class="cancel">X</span>
  </div>
  <div class="listWrapper">
    <div class="tpl hide">
      <h3>暂时不支持更换模板, 功能开发中, 请下次再来, 谢谢.</h3>
    </div>
    <div class="music hide">
      <div class="music-tab">
        <ul class="li_style sub-nav">
          <li class="all" class="active">
            <a class="a-style" href="#">所有</a>
          </li>
          <li class="fashion">
            <a class="a-style" href="#">流行</a>
          </li>
          <li class="english">
            <a class="a-style" href="#">英文</a>
          </li>
          <li class="pure">
            <a class="a-style" href="#">纯音乐</a>
          </li>
        </ul>
      </div>
      <div class="music-category all ">
        <% @songs.each_with_index do |song, i| %>
          <div class="row" data-song-id="<%= song.id %>" data-song-src="<%= song.src %>">
            <div class="small-12 columns">
              <%= "#{i} #{song.name} -- #{song.singer} " %>
              <div class="indicator"></div>
              <a href="#" class="button tiny pick">使用</a>
            </div>
          </div>
        <% end %>
      </div>
      <div class="music-category fashion hide">
        <% fashion = @songs.find_all { |song| song.category == '流行' } %>
        <% fashion.each_with_index do |song, i| %>
          <div class="row" data-song-id="<%= song.id %>" data-song-src="<%= song.src %>">
            <div class="small-12 columns">
              <%= "#{i} #{song.name} -- #{song.singer} " %>
              <div class="indicator"></div>
              <a href="#" class="button tiny pick">使用</a>
            </div>
          </div>
        <% end %>
      </div>
      <div class="music-category english hide">
        <% english = @songs.find_all { |song| song.category == '英文' } %>
        <% english.each_with_index do |song, i| %>
          <div class="row" data-song-id="<%= song.id %>" data-song-src="<%= song.src %>">
            <div class="small-12 columns">
              <%= "#{i} #{song.name} -- #{song.singer} " %>
              <div class="indicator"></div>
              <a href="#" class="button tiny pick">使用</a>
            </div>
          </div>
        <% end %>
      </div>
      <div class="music-category pure hide">
        <% pure = @songs.find_all { |song| song.category == '纯音乐' } %>
        <% pure.each_with_index do |song, i| %>
          <div class="row" data-song-id="<%= song.id %>" data-song-src="<%= song.src %>">
            <div class="small-12 columns">
              <%= "#{i} #{song.name}  #{song.singer} " %>
              <div class="indicator"></div>
              <a href="#" class="button tiny pick">使用</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="pics hide">
      <ul class="small-block-grid-3" style="margin: 0rem;">
        <% @album.images.each do |image| %>
          <li>
            <div class="delPhotos">
              <img data-id="<%= image.id %>" src="<%= image.url %>">
              <a class="delPhoto" href="#">X</a>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="title hide">
      <%= form_for @album, url: {action: "update"} do |f| %>
        <span class="title-lead">给您的微海报写个标题吧</span>
        <%= f.text_area :name, value: "我的微海报", class: "title-content" %>
        <%= f.hidden_field :status, value: "published" %>
        <input type="hidden" id="openid" name="openid" value="<%= @album.user.openid %>"/>
        <button type="submit" class="publish small">写好标题了, 发布</button>
      <% end %>
    </div>
  </div>
</div>

<div class="music-icon play" id="music-icon"></div>
<input type="hide" id="albumId" value="<%= @album.id %>" />

<audio id="audio" src="<%= @album.song.src %>" autoplay="autoplay" loop="loop">
  <h1>您的浏览器不支持 audio 标签。</h1>
</audio>

<%= hidden_field_tag(:cfg, "0", data:{appid: @appid, timestamp: @cfg[:timestamp], noncestr: @cfg[:noncestr], signature: @cfg[:signature], url: @cfg[:url], jsapi_ticket: @cfg[:jsapi_ticket]}) %>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', user_albums_path(@album.user) %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="my-album">
  <% @albums.each do |album| %>
    <li>
      <div class="time-circle">
        <p class="album-date"><%= album.created_at.strftime('%m-%d') %></p>
        <p class="album-year"><%= album.created_at.year %></p>
      </div>
      <div class="right-content">
        <h6><%= album.name %></h6>
        <div class="photo-container">
          <div class="photo-cover" style="background-image: url(<%= album.images.first.url %>)">
          </div>
        </div>
        <div class="album-manage">
          <%= link_to '查看', album_path(album), class: "edit-album button info tiny" %>
          <%= link_to '删除', album_path(album, params: {openid: album.user.openid}), class: "delete-album button info tiny", method: :delete, data: { confirm: "确定删除?" }%>
        </div>
      </div>
    </li>
  <% end %>
</ul>

<% if @albums.length == 0 %>
<div style="text-align:center">
  <h3 style="color:red">你还没有微海报~</h3>
  <p>有声有色微海报, 好听好看悦分享</p>
  <% cover = "http://#{WECHAT_CONFIG[:domain]}/images/albums_cover.jpg" %>
  <img src="<%= cover %>"/>
  <p>
  炫酷的动画效果，好听的音乐， 配上你精心拍好的照片, 微海报是全新的分享方式.
  关注微海报, 微信直接上传图片制作, 简单几步就可以做出漂亮的海报！全部免费！快来开始吧~
  </p>
  <a href="/pages/faq" class="button tiny radius alert">常见问题</a>
</div>
<% end %>

app/views/albums/new.html.erb
<h1>新建相册</h1>

<%= render 'form' %>

<%= link_to 'Back', user_albums_path %>

app/views/albums/show.html.erb
<div id="fullpage" class="text-center">
  <% @album.images.each do |image| %>
    <div class="section"><img src="<%= image.url %>"></div>
  <% end %>
</div>

<div class="album arrow-wrapper animated fadeOutUp">
  <p class="arrow"></p>
</div>

<div class="suscribe">
    <a href="http://mp.weixin.qq.com/s?__biz=MzAxOTQ4MDkyOA==&mid=209932994&idx=1&sn=a0f2a0e25c1bc34696ce8d4e79fea56b#rd">自己做相册</a>
</div>


<div class="music-icon play" id="music-icon"></div>
<audio id="audio" src="<%= @album.song.src %>" autoplay="autoplay" loop="loop">
  <h1>您的浏览器不支持 audio 标签。</h1>
</audio>